metrics:
  crypto:
    url: 
      - "https://coinmarketcap.com/currencies/avalanche/"
      - "https://coinmarketcap.com/currencies/ethereum/"
      - "https://coinmarketcap.com/currencies/bitcoin/"
      - "https://coinmarketcap.com/currencies/api3/"
      - "https://coinmarketcap.com/currencies/fantom/"
      - "https://coinmarketcap.com/currencies/dogecoin/"
      - "https://coinmarketcap.com/currencies/usd-coin/"
      - "https://coinmarketcap.com/currencies/cardano/"
      - "https://coinmarketcap.com/currencies/cronos/"
    type: gauge
    description: "Exports the current coin value based on the web scrape"
